config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#term'
  get 'contact', to: 'static_pages#contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'

  resources :users, only: %i[new create show]
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :notifications, only: %i[index] do
    patch :read, on: :member
  end
end

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar navbar-expand-lg navigation navbar-light header-content">
    <a class='navbar-brand' href='/'>
      <%= image_tag 'header-logo.png', size: '70x70', class: "ms-5" %>
    </a>
    <nav class="my-2 my-md-0 ms-auto">
      <%= link_to (t 'defaults.login'), login_path, class: "p-2 link" %>
      <%= link_to 'ゲストログイン', '/guest_login', data: { "turbo-method": :post }, class: "p-2 link" %>
    </nav>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-5 px-2 border-top footer-content">
  <p class="col-md-4 mb-0 text-body-secondary">Copyright © 2023. アアイエバ For You</p>

  <ul class="nav col-md-4 justify-content-end">
    <li class="nav-item pe-4"><%= link_to '利用規約', terms_path, class: "link" %></li>
    <li class="nav-item pe-4"><%= link_to 'プライバシーポリシー', privacy_path, class: "link" %></li>
    <li class="nav-item pe-4"><%= link_to 'お問い合わせ', contact_path, class: "link" %></li>
  </ul>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light header-content">
    <a class='navbar-brand' href='/'>
      <%= image_tag 'header-logo.png', size: '70x70', class: "ms-5" %>
    </a>
    <button class="navbar-toggler me-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbar">
      <div class="navbar-nav ml-auto ms-auto">
        <%= link_to t('posts.index.title'), posts_path, class: "p-2 link" %>
        <%= link_to t('posts.new.title'), new_post_path, class: "p-2 link" %>
        <%= link_to "通知", notifications_path, class: "p-2 link" %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle p-2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            マイページ
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "マイページ", user_path(current_user.id), class: "link dropdown-item" %></li>
            <li><%= link_to '登録情報編集', edit_profile_path, class: "link dropdown-item" %></li>
          </ul>
        </li>
        <%= link_to (t 'defaults.logout'), logout_path, data: { "turbo-method": :delete }, class: "p-2 link" %>
      </div>
    </div>
  </nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</header>