config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'static_pages#top'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#term'
  get 'contact', to: 'static_pages#contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post '/guest_login', to: 'user_sessions#guest_login'

  resources :users, only: %i[new create show]
  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
  end
  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :notifications, only: %i[index] do
    patch :read, on: :member
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id            :bigint           not null, primary key
#  episode       :text
#  image         :string
#  partners_word :text             not null
#  word          :text             not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  genre_id      :bigint
#  partner_id    :bigint
#  situation_id  :bigint
#  user_id       :bigint           not null
#
# Indexes
#
#  index_posts_on_genre_id      (genre_id)
#  index_posts_on_partner_id    (partner_id)
#  index_posts_on_situation_id  (situation_id)
#  index_posts_on_user_id       (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  mount_uploader :image, PostImageUploader

  belongs_to :user
  belongs_to :genre
  belongs_to :partner
  belongs_to :situation
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user

  validates :word, presence: true, length: { maximum: 255 }
  validates :episode, length: { maximum: 65_535 }
  validates :partners_word, presence: true, length: { maximum: 255 }

  def self.ransackable_associations(auth_object = nil)
    %w[genre partner situation]
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[word partners_word episode]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post_details, only: %i[new create edit update]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @genre = @post.genre.name
    @partner = @post.partner.name
    @situation = @post.situation.name
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: t('defaults.message.created', item: Post.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: Post.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, success: t('defaults.message.updated', item: Post.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Post.model_name.human)
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, success: t('defaults.message.deleted', item: Post.model_name.human)
  end

  private

  def set_post_details
    @genres = Genre.all
    @partners = Partner.all
    @situations = Situation.all
  end

  def post_params
    params.require(:post).permit(:word, :image, :episode, :partners_word, :genre_id, :partner_id, :situation_id, :name, :image_cache)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to edit_post_path(post), id: "button-edit-#{post.id}" do %>
      <i class="fa-regular fa-pen-to-square fa-lg" style="color: #446878;"></i>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to post_path(post), data: { "turbo-method": :delete, turbo_confirm: t('defaults.message.delete_confirm') }, id: "button-delete-#{post.id}" do %>
      <i class="fa-solid fa-trash-can fa-lg" style="color: #446878;"></i>
    <% end %>
  </li>
</ul>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="container mt-5">
    <div class="row">
      <div class="form-group col-auto">
        <%= f.label :partner %>
        <%= f.collection_select :partner_id, @partners, :id, :name, prompt: "選択してください" %>
      </div>
      <div class="form-group col-auto">
        <%= f.label :genre %>
        <%= f.collection_select :genre_id, @genres, :id, :name, prompt: "選択してください" %>
      </div>
      <div class="form-group col-auto">
        <%= f.label :situation %>
        <%= f.collection_select :situation_id, @situations, :id, :name, prompt: "選択してください" %>
      </div>
    </div>
    <div>
      <div class="form-group mt-4 mb-2">
        <%= f.label :partners_word %>
        <%= f.text_area :partners_word, class: 'form-control' %>
      </div>
      <div class="form-group my-2">
        <%= f.label :word %>
        <%= f.text_area :word, class: 'form-control' %>
      </div>
      <div class="form-group my-2">
        <%= f.label :episode %>
        <%= f.text_area :episode, class: 'form-control' %>
      </div>
      <div class="form-group my-2">
        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control mb-3', accept: 'image/*' %>
        <%= f.hidden_field :image_cache %>
      </div>

      <%= f.submit class: 'btn btn-light mb-3' %>
    </div>
  </div>
<% end %>

app/views/posts/_like.html.erb
<%= link_to likes_path(post_id: post.id),
            id: "js-like-button-for-post-#{post.id}",
            class: "float-right link",
            data: { "turbo-method": :post } do %>
  <i class="fa-regular fa-heart fa-lg" style="color: #446878;"></i> <%= post.likes.count %>
<% end %>

app/views/posts/_like_button.html.erb
<div id="like-button-<%= post.id %>">
  <% if current_user.like?(post) %>
    <%= render 'posts/unlike', { post: post } %>
  <% else %>
    <%= render 'posts/like', { post: post } %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="card-deck">
  <div class="card mb-2 h-100 post-content">
    <div class="row g-0">
      <div class="col-md-4 p-md-2">
        <%= image_tag post.image_url, class: "img-fluid rounded m-4", size: "200x200" %>
      </div>
      <div class="col-md-8">
        <%= link_to post, class: "card-body", style: "text-decoration:none", data: { turbo_action: :advance } do %>
          <h2 class="card-text d-flex align-items-center justify-content-center my-4 balloon-post">
            <%= post.word %>
          </h2>
        <% end %>
        <div class="text-center" >
          # <%= link_to post.partner.name, posts_path(@q, :'q[partner_id_eq]' => "#{post.partner.id}"), class: "link" %>&emsp;
          # <%= link_to post.genre.name, posts_path(@q, :'q[genre_id_eq]' => "#{post.genre.id}"), class: "link" %>&emsp;
          # <%= link_to post.situation.name, posts_path(@q, :'q[situation_id_eq]' => "#{post.situation.id}"), class: "link" %>
        </div>
        <div class="me-4", align="right">
          <% if current_user.own?(post) %>
            <%= render 'posts/crud_menus', post: post %>
          <% else %>
            <%= render 'posts/like_button', post: post  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_search_form.html.erb
<%= search_form_for @q, url: url, html: { data: { turbo_frame: "posts-list", controller: "search", action: "input->search#submit" } } do |f| %>
  <div class="input-group mb-3 search-content">
    <%= f.search_field :word_or_partners_word_or_episode_cont, class: 'form-control me-1', placeholder: t('defaults.search_word') %>
    <%= f.select :partner_id_eq, options_from_collection_for_select(Partner.all, :id, :name, @q.partner_id_eq), { include_blank: '-会話の相手-' }, class: "mx-1" %>
    <%= f.select :genre_id_eq, options_from_collection_for_select(Genre.all, :id, :name, @q.genre_id_eq), { include_blank: '-ジャンル-' }, class: "mx-1" %>
    <%= f.select :situation_id_eq, options_from_collection_for_select(Situation.all, :id, :name, @q.situation_id_eq), { include_blank: '-シチュエーション-' }, class: "ms-1 me-2" %>
  </div>
<% end %>

app/views/posts/_unlike.html.erb
<%= link_to like_path(current_user.likes.find_by(post_id: post.id)),
            class: "float-right link",
            data: { "turbo-method": :delete } do %>
  <i class="fa-solid fa-heart fa-lg" style="color: #446878;"></i> <%= post.likes.count %>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <%= render 'search_form', url: posts_path %>
      <%= turbo_frame_tag "posts-list" do %>
        <div class="row row-cols-2 row-cols-md-2 g-2">
          <% if @posts.present? %>
            <%= render @posts %>
          <% else %>
            <p><%= t('.no_result') %></p>
          <% end %>
        </div>
        <div class="mt-2">
          <%= paginate @posts %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/likes.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <div class="input-group mb-3">
          <input class="form-control" placeholder="検索ワード" type="search" />
          <div class="input-group-append">
            <input type="submit" value="検索" class="btn btn-primary" />
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @like_posts.present? %>
          <%= render @like_posts %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <div class="mt-2">
        <%= paginate @like_posts %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2 post-content">
      <h1 class="text-center"><%= t('.title') %></h1>
      <%= render 'form', { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="row g-0">
  <div class="col-xl-8 pe-2">
    <div class="card mb-2 h-100 post-show-content">
      <div class="card-header">
        <div class="d-flex flex-column flex-md-row align-items-center p-1 px-md-4 mb-1">
          <%= @post.user.name %>さんの投稿
          <nav class="my-2 my-md-0 ms-auto">
            <% if current_user.own?(@post) %>
              <%= link_to edit_post_path(@post), class: "p-2 link" do %>
                <i class="fa-regular fa-pen-to-square fa-lg" style="color: #446878;"></i>
              <% end %>
              <%= link_to post_path(@post), data: { "turbo-method": :delete, turbo_confirm: t('defaults.message.delete_confirm') }, class: "p-2 link" do %>
                <i class="fa-solid fa-trash-can fa-lg" style="color: #446878;"></i>
              <% end %>
              <i class="fa-solid fa-heart fa-lg ms-2" style="color: #446878;"></i> <%= @post.likes.count %>
            <% else %>
              <%= render 'posts/like_button', post: @post  %>
            <% end %>
          </nav>
        </div>
      </div>
      <div class="row g-0">
        <div class="col-sm-3 p-md-2">
          <%= image_tag 'post-default.jpg', class: "img-fluid rounded m-4", size: '200x200' %>
        </div>
        <div class="col-sm-9">
          <h2 class="card-text d-flex align-items-center justify-content-center my-4 balloon-show-left">
            <%= @post.partners_word %>
          </h2>
        </div>
        <div class="col-sm-3 p-md-2">
          <%= image_tag @post.image_url, class: "img-fluid rounded m-4", size: "200x200" %>
        </div>
        <div class="col-sm-9">
          <h2 class="card-text d-flex align-items-center justify-content-center my-4 balloon-show-right">
            <%= @post.word %>
          </h2>
        </div>
      </div>
      <div class="card-footer episode-content m-2">
        <h2 class="card-text d-flex align-items-center justify-content-center my-4">
          <%= @post.episode %>
        </h2>
      </div>
    </div>
  </div>

  <div class="col-xl-4">
    <div class="card mb-2 h-100 post-comment-content">
      <div class="card-header">
        <div class="d-flex flex-column flex-md-row align-items-center p-1 px-md-4 mb-1">
          コメント一覧
        </div>
      </div>
      <div class="row g-0 pt-2 comment-index-content">
        <%= render 'comments/comments', { comments: @comments } %>
      </div>
      <div class="row g-0 pt-2">
        <%= render 'comments/form', { post: @post, comment: @comment } %>
      </div>
    </div>
  </div>
</div>